from mal.spiders.anime.helpers.details.__aired_from import aired_from_helper
from mal.spiders.anime.helpers.details.__aired_to import aired_to_helper
from mal.spiders.anime.helpers.details.__background import background_helper
from mal.spiders.anime.helpers.details.__duration import duration_helper
from mal.spiders.anime.helpers.details.__episodes import episodes_helper
from mal.spiders.anime.helpers.details.__genres import genres_helper
from mal.spiders.anime.helpers.details.__licensors import licensors_helper
from mal.spiders.anime.helpers.details.__premiered import premiered_helper
from mal.spiders.anime.helpers.details.__producers import producers_helper
from mal.spiders.anime.helpers.details.__rating import rating_helper
from mal.spiders.anime.helpers.details.__score import score_helper
from mal.spiders.anime.helpers.details.__studios import studios_helper
from mal.spiders.anime.helpers.details.__synonyms import synonyms_helper
from mal.spiders.anime.helpers.details.__synopsis import synopsis_helper
from mal.spiders.anime.helpers.details.__trailer import trailer_helper
